server:
  port: 8031
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
turbine:
  #要监控的服务列表,多个,分割
  app-config: service-order
  cluster-name-expression: "'defalut'"
