server:
  port: 7001
spring:
  application:
    name: stream-comsumer
  rabbitmq:
    addresses: 192.168.0.6
    username: yokea
    password: 123456
    port: 5672
  cloud:
    stream:
      bindings:
        myinput:
          destination: default
          group: group1
          consumer:
            partitioned: true  #开启分区支持
      binders:
          defaultRabbit:
            type: rabbit
      instance-count: 2   #消费者总数
      instance-index: 0    #当前消费者索引


