server:
  port: 9001
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  #zipkin使用rabbitmq采集数据
  zipkin:
    #base-url: http://localhost:9411/      #server的请求地址
    sender:
      #type: web     #数据的传输方式,以Http的形式向server端发送数据
      type: rabbit
  sleuth:
    sampler:
      probability: 1   #采样比   收集所有的数据
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:   #配置重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
eureka:
  client:
    service-url:
     # defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/  #注册多个euraka
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true     #使用ip地址注册,方便eureka后台查看
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}
   # lease-expiration-duration-in-seconds: 5     #发送心跳间隔,默认30S
   # lease-renewal-interval-in-seconds: 10          #设置续约时间,多少秒没心跳,则默认宕机,剔除服务.默认90S

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
