server:
  port: 7002
spring:
  application:
    name: stream-comsumer
  rabbitmq:
    addresses: 192.168.0.6
    username: yokea
    password: 123456
    port: 5672
  cloud:
    stream:
      bindings:
        #output:
        myoutput:
          destination: default
          producer:
            partition-key-expression: payload      #分区关键字
            partition-count: 2  #分区大小
      binders:    #配置绑定器
        defaultRabbit:
          type: rabbit
